name: Build Workflow V1

on: 
    push: 
        branches: ["main"]
jobs:
   testing:
        runs-on: ubuntu-latest
        steps:
            - name: Print String
              run: echo "hello world"
    