name: Angular CI
# Triggers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Manual work flow activation
  workflow_dispatch:

# Jobs
jobs:

  #Test
  test:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{steps.publish}}
    steps: 
    - name: Get Code
      uses: actions/checkout@v3
    # cache
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json)')}}
    - name: Install Dependencies
      run: npm ci
    # Install Angular 
    - name: Install Angular cli
      run: npm install -g @angular/cli

    # Test Code
    - name: Test Code Step
      run: echo "Running tests......."
    



  # Build
  build:
    needs: test
    # Runner
    runs-on: ubuntu-latest
    steps:

    # CHECKOUT
    - name: Get Code
      uses: actions/checkout@v3

      #NODE
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'  # Specify Node.js version
    - name: Install dependencies
      run: npm ci 
   
      # INSTALL ANGUALR
    - name: Install Angular CLI
      run: npm install -g @angular/cli 

      # BUILD
    - name: Build
      run: ng build
        
    # - name: Run tests
    #   run: ng test
        # Note: Update test command for CI compatibility once implemented
