name: Angular CI
# Triggers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Manual work flow activation
  workflow_dispatch:

# Jobs
jobs:

  #Test
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Get Code
      uses: actions/checkout@v4
    # Custom Composite Action Load and Cache deps
    - name: Load & Cache Dependencies
      uses: ./.github/actions/cached-deps
    # Install Angular 
    - name: Install Angular cli
      run: npm install -g @angular/cli

    # Test Code
    - name: Test Code Step
      id: test-code-step
     # Continue on error check
      # So the next steps and jobs will be executed even if this test code step fails
      continue-on-error: true
      run: ng test --watch=false --browsers=ChromeHeadless > test-report.txt
    
    # Upload results 
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test report
        path: test-report.txt
    
    


  # Build
  build:
    needs: test
    # Runner
    runs-on: ubuntu-latest
    steps:

    # CHECKOUT
    - name: Get Code
      uses: actions/checkout@v4
    
       # Custom Composite Action Load and Cache deps
    - name: Load & Cache Dependencies
      uses: ./.github/actions/cached-deps

    #   #NODE
    # - name: Set up Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '18.16.0'  # Specify Node.js version
    # - name: Install dependencies
    #   run: npm ci 
   
      # INSTALL ANGUALR
    - name: Install Angular CLI
      run: npm install -g @angular/cli 

      # BUILD
    - name: Build
      run: ng build

      # Upload build files
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: dist
        
    
    