name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        
    - name: Get Code
      uses: actions/checkout@v3

    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '5.2.0'  # Specify Node.js version
    - name: Install dependencies
      run: npm ci
  
    - name: Build
      run: ng build
  
    - name: Run tests
      run: ng test
        # Note: Update test command for CI compatibility once implemented
